# Mobile apps are everywhere. They are easy to create and can be very lucrative from the business standpoint. Specifically, Android is expanding as an operating system and has captured more than 74% of the total market.

# The Google Play Store apps data has enormous potential to facilitate data-driven decisions and insights for businesses. In this notebook, I analyzed the Android app market by comparing ~10k apps in Google Play across different categories. I also used the user reviews to draw a qualitative comparision between the apps.

In [52]:
import pandas as pd
import numpy as np
apps = pd.read_csv('datasets/apps.csv')
apps.info()
apps.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   App           9659 non-null   object
 1   Category      9659 non-null   object
 2   Rating        8196 non-null   float64
 3   Reviews       9659 non-null   int64
 4   Size          8432 non-null   float64
 5   Installs      9659 non-null   object
 6   Type          9659 non-null   object
 7   Price         9659 non-null   float64
 8   Last Updated  9659 non-null   object
dtypes: float64(3), int64(1), object(5)
memory usage: 679.3+ KB

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0.0,"June 20, 2018"

In [53]:
characters = [',', '+']
for char in characters:
    apps['Installs'] = apps['Installs'].apply(lambda x: x.replace(char, '') )
    
apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,"June 20, 2018"
...,...,...,...,...,...,...,...,...,...
9654,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0.0,"July 25, 2017"
9655,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0.0,"July 6, 2018"
9656,Parkinson Exercices FR,MEDICAL,NaN,3,9.5,1000,Free,0.0,"January 20, 2017"
9657,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,"January 19, 2015"
9658,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,"July 25, 2018"

In [54]:
apps['Installs'] = apps['Installs'].astype(int)
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,"June 20, 2018"

In [55]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   App           9659 non-null   object
 1   Category      9659 non-null   object
 2   Rating        8196 non-null   float64
 3   Reviews       9659 non-null   int64
 4   Size          8432 non-null   float64
 5   Installs      9659 non-null   int32
 6   Type          9659 non-null   object
 7   Price         9659 non-null   float64
 8   Last Updated  9659 non-null   object
dtypes: float64(3), int32(1), int64(1), object(4)
memory usage: 641.5+ KB

In [56]:
app_category_info = apps.groupby('Category').agg({'App':'count', 'Rating':'mean', 'Price':'mean'})
app_category_info

                      App    Rating     Price
Category
ART_AND_DESIGN         64  4.357377  0.093281
AUTO_AND_VEHICLES      85  4.190411  0.158471
BEAUTY                 53  4.278571  0.000000
BOOKS_AND_REFERENCE   222  4.344970  0.539505
BUSINESS              420  4.098479  0.417357
COMICS                 56  4.181481  0.000000
COMMUNICATION         315  4.121484  0.263937
DATING                171  3.970149  0.160468
EDUCATION             119  4.364407  0.150924
ENTERTAINMENT         102  4.135294  0.078235
EVENTS                 64  4.435556  1.718594
FAMILY               1832  4.179664  1.309967
FINANCE               345  4.115563  8.408203
FOOD_AND_DRINK        112  4.172340  0.075714
GAME                  959  4.247368  0.296465
HEALTH_AND_FITNESS    288  4.243033  0.223438
HOUSE_AND_HOME         74  4.150000  0.000000
LIBRARIES_AND_DEMO     84  4.178125  0.011786
LIFESTYLE             369  4.093355  6.398022
MAPS_AND_NAVIGATION   131  4.036441  0.205725
MEDICAL               395  4.166552  2.520759
NEWS_AND_MAGAZINES    254  4.121569  0.015669
PARENTING              60  4.300000  0.159667
PERSONALIZATION       376  4.332215  0.400213
PHOTOGRAPHY           281  4.157414  0.420925
PRODUCTIVITY          374  4.183389  0.670936
SHOPPING              202  4.230000  0.027129
SOCIAL                239  4.247291  0.066820
SPORTS                325  4.216154  0.307692
TOOLS                 827  4.039554  0.323156
TRAVEL_AND_LOCAL      219  4.069519  0.228082
VIDEO_PLAYERS         163  4.044595  0.064172
WEATHER                79  4.243056  0.410380

In [57]:
app_category_info = app_category_info.rename(columns={'App':'Number of apps', 'Price':'Average price', 'Rating':'Average rating'})
app_category_info

                     Number of apps  Average rating  Average price
Category
ART_AND_DESIGN                   64        4.357377       0.093281
AUTO_AND_VEHICLES                85        4.190411       0.158471
BEAUTY                           53        4.278571       0.000000
BOOKS_AND_REFERENCE             222        4.344970       0.539505
BUSINESS                        420        4.098479       0.417357
COMICS                           56        4.181481       0.000000
COMMUNICATION                   315        4.121484       0.263937
DATING                          171        3.970149       0.160468
EDUCATION                       119        4.364407       0.150924
ENTERTAINMENT                   102        4.135294       0.078235
EVENTS                           64        4.435556       1.718594
FAMILY                         1832        4.179664       1.309967
FINANCE                         345        4.115563       8.408203
FOOD_AND_DRINK                  112        4.172340       0.075714
GAME                            959        4.247368       0.296465
HEALTH_AND_FITNESS              288        4.243033       0.223438
HOUSE_AND_HOME                   74        4.150000       0.000000
LIBRARIES_AND_DEMO               84        4.178125       0.011786
LIFESTYLE                       369        4.093355       6.398022
MAPS_AND_NAVIGATION             131        4.036441       0.205725
MEDICAL                         395        4.166552       2.520759
NEWS_AND_MAGAZINES              254        4.121569       0.015669
PARENTING                        60        4.300000       0.159667
PERSONALIZATION                 376        4.332215       0.400213
PHOTOGRAPHY                     281        4.157414       0.420925
PRODUCTIVITY                    374        4.183389       0.670936
SHOPPING                        202        4.230000       0.027129
SOCIAL                          239        4.247291       0.066820
SPORTS                          325        4.216154       0.307692
TOOLS                           827        4.039554       0.323156
TRAVEL_AND_LOCAL                219        4.069519       0.228082
VIDEO_PLAYERS                   163        4.044595       0.064172
WEATHER                          79        4.243056       0.410380

In [58]:
reviews = pd.read_csv('datasets/user_reviews.csv')
reviews.info()
reviews.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   App                 64295 non-null  object
 1   Review              37427 non-null  object
 2   Sentiment Category  37432 non-null  object
 3   Sentiment Score     37432 non-null  float64
dtypes: float64(1), object(3)
memory usage: 2.0+ MB

,App,Review,Sentiment Category,Sentiment Score
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25
2,10 Best Foods for You,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40
4,10 Best Foods for You,Best idea us,Positive,1.00

In [59]:
finance_apps = apps[apps['Category']=='FINANCE']
finance_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
837,K PLUS,FINANCE,4.4,124424,NaN,10000000,Free,0.0,"June 26, 2018"
838,ING Banking,FINANCE,4.4,39041,NaN,1000000,Free,0.0,"August 3, 2018"
839,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018"
840,The postal bank,FINANCE,3.7,36718,NaN,5000000,Free,0.0,"July 16, 2018"
841,KTB Netbank,FINANCE,3.8,42644,19.0,5000000,Free,0.0,"June 28, 2018"
...,...,...,...,...,...,...,...,...,...
9540,BankNordik,FINANCE,3.9,28,15.0,5000,Free,0.0,"August 8, 2018"
9564,FP Markets,FINANCE,NaN,1,2.0,100,Free,0.0,"January 30, 2018"
9565,FP Boss,FINANCE,NaN,1,5.8,1,Free,0.0,"July 27, 2018"
9572,FP FCU,FINANCE,3.6,48,26.0,5000,Free,0.0,"April 5, 2018"
9636,Gold Quote - Gold.fr,FINANCE,NaN,96,1.5,10000,Free,0.0,"May 19, 2016"

In [60]:
free_finance_apps = finance_apps[finance_apps['Type']=='Free']

In [61]:
free_finance_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
837,K PLUS,FINANCE,4.4,124424,NaN,10000000,Free,0.0,"June 26, 2018"
838,ING Banking,FINANCE,4.4,39041,NaN,1000000,Free,0.0,"August 3, 2018"
839,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018"
840,The postal bank,FINANCE,3.7,36718,NaN,5000000,Free,0.0,"July 16, 2018"
841,KTB Netbank,FINANCE,3.8,42644,19.0,5000000,Free,0.0,"June 28, 2018"
...,...,...,...,...,...,...,...,...,...
9540,BankNordik,FINANCE,3.9,28,15.0,5000,Free,0.0,"August 8, 2018"
9564,FP Markets,FINANCE,NaN,1,2.0,100,Free,0.0,"January 30, 2018"
9565,FP Boss,FINANCE,NaN,1,5.8,1,Free,0.0,"July 27, 2018"
9572,FP FCU,FINANCE,3.6,48,26.0,5000,Free,0.0,"April 5, 2018"
9636,Gold Quote - Gold.fr,FINANCE,NaN,96,1.5,10000,Free,0.0,"May 19, 2016"

In [62]:
merged_df = pd.merge(reviews,free_finance_apps, on= 'App')
merged_df

,App,Review,Sentiment Category,Sentiment Score,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,A+ Mobile,NaN,NaN,NaN,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
1,A+ Mobile,"I rated higher, lowering rating. It simply wor...",Negative,-0.063889,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
2,A+ Mobile,NaN,NaN,NaN,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
3,A+ Mobile,NaN,NaN,NaN,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
4,A+ Mobile,It tells I need update option update. So I uni...,Positive,0.156250,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
...,...,...,...,...,...,...,...,...,...,...,...,...
2195,HDFC Bank MobileBanking,"I cant access When need this, stop Error shown...",Negative,-0.500000,FINANCE,4.2,208463,NaN,10000000,Free,0.0,"July 26, 2018"
2196,HDFC Bank MobileBanking,I even able login. It recognising customer Id....,Positive,0.466667,FINANCE,4.2,208463,NaN,10000000,Free,0.0,"July 26, 2018"
2197,HDFC Bank MobileBanking,"It working gives msg ""please enable Google pla...",Positive,0.033333,FINANCE,4.2,208463,NaN,10000000,Free,0.0,"July 26, 2018"
2198,HDFC Bank MobileBanking,Need finger print security. Under account summ...,Negative,-0.090000,FINANCE,4.2,208463,NaN,10000000,Free,0.0,"July 26, 2018"
2199,HDFC Bank MobileBanking,For Credit Card payment electing Minimum / Oth...,Negative,-0.036111,FINANCE,4.2,208463,NaN,10000000,Free,0.0,"July 26, 2018"

In [63]:
app_sentiment_score = merged_df.groupby('App').agg({'Sentiment Score':'mean'})
app_sentiment_score

                                                 Sentiment Score
App
A+ Mobile                                               0.329592
ACE Elite                                               0.252171
Acorns - Invest Spare Change                            0.046667
Amex Mobile                                             0.175666
Associated Credit Union Mobile                          0.388093
BBVA Compass Banking                                    0.205590
BBVA Spain                                              0.515086
BZWBK24 mobile                                          0.326883
Bank of America Mobile Banking                          0.180027
BankMobile Vibe App                                     0.353455
Banorte Movil                                           0.116999
Barclays US for Android                                 0.017928
Betterment                                              0.143252
Bloomberg Professional                                 -0.023353
Bluebird by American Express                                 NaN
Branch                                                  0.264230
Bualuang mBanking                                       0.004322
CNBC: Breaking Business News & Live Market Data         0.247704
Capital One® Mobile                                          NaN
Capitec Remote Banking                                       NaN
Cash App                                                     NaN
Chase Mobile                                            0.048166
Chime - Mobile Banking                                       NaN
Citi Mobile®                                           -0.038731
Citibanamex Movil                                       0.150061
Citizens Bank Mobile Banking                            0.013179
Credit Karma                                            0.270052
Credit Sesame                                           0.088667
CreditWise from Capital One                             0.239454
Current debit card and app made for teens               0.327258
Digit Save Money Automatically                          0.250246
Discover Mobile                                        -0.041667
E*TRADE Mobile                                          0.153273
Ecobank Mobile Banking                                 -0.014860
Even - organize your money, get paid early              0.283929
Everlance: Free Mileage Log                                  NaN
Expense IQ Money Manager                                0.227506
Experian - Free Credit Report                           0.170504
FREE Stock Market Trading Tips                               NaN
Fortune City - A Finance App                            0.266966
Fox Business                                            0.088827
Fresh EBT - Food Stamp Balance                          0.159727
GCash - Buy Load, Pay Bills, Send Money                 0.027082
GoBank                                                  0.039101
Google Pay                                              0.115687
HDFC Bank MobileBanking                                 0.111449

In [64]:
app_sentiment_score_srt = app_sentiment_score.sort_values(by = 'Sentiment Score', ascending = False)
app_sentiment_score_srt

                                                 Sentiment Score
App
BBVA Spain                                              0.515086
Associated Credit Union Mobile                          0.388093
BankMobile Vibe App                                     0.353455
A+ Mobile                                               0.329592
Current debit card and app made for teens               0.327258
BZWBK24 mobile                                          0.326883
Even - organize your money, get paid early              0.283929
Credit Karma                                            0.270052
Fortune City - A Finance App                            0.266966
Branch                                                  0.264230
ACE Elite                                               0.252171
Digit Save Money Automatically                          0.250246
CNBC: Breaking Business News & Live Market Data         0.247704
CreditWise from Capital One                             0.239454
Expense IQ Money Manager                                0.227506
BBVA Compass Banking                                    0.205590
Bank of America Mobile Banking                          0.180027
Amex Mobile                                             0.175666
Experian - Free Credit Report                           0.170504
Fresh EBT - Food Stamp Balance                          0.159727
E*TRADE Mobile                                          0.153273
Citibanamex Movil                                       0.150061
Betterment                                              0.143252
Banorte Movil                                           0.116999
Google Pay                                              0.115687
HDFC Bank MobileBanking                                 0.111449
Fox Business                                            0.088827
Credit Sesame                                           0.088667
Chase Mobile                                            0.048166
Acorns - Invest Spare Change                            0.046667
GoBank                                                  0.039101
GCash - Buy Load, Pay Bills, Send Money                 0.027082
Barclays US for Android                                 0.017928
Citizens Bank Mobile Banking                            0.013179
Bualuang mBanking                                       0.004322
Ecobank Mobile Banking                                 -0.014860
Bloomberg Professional                                 -0.023353
Citi Mobile®                                           -0.038731
Discover Mobile                                        -0.041667
Bluebird by American Express                                 NaN
Capital One® Mobile                                          NaN
Capitec Remote Banking                                       NaN
Cash App                                                     NaN
Chime - Mobile Banking                                       NaN
Everlance: Free Mileage Log                                  NaN
FREE Stock Market Trading Tips                               NaN

In [65]:
top_10_user_feedback = app_sentiment_score_srt[:10]

In [66]:
top_10_user_feedback

                                            Sentiment Score
App
BBVA Spain                                         0.515086
Associated Credit Union Mobile                     0.388093
BankMobile Vibe App                                0.353455
A+ Mobile                                          0.329592
Current debit card and app made for teens          0.327258
BZWBK24 mobile                                     0.326883
Even - organize your money, get paid early         0.283929
Credit Karma                                       0.270052
Fortune City - A Finance App                       0.266966
Branch                                             0.264230